    .section .text.entry
    .align 4
    .globl _traps
_traps:
    # 1. 将寄存器和 sepc 保存到栈上
    addi sp, sp, -256
    sd x1, 0(sp)
    sd x2, 8(sp)
    sd x3, 16(sp)
    sd x4, 24(sp)
    sd x5, 32(sp)
    sd x6, 40(sp)
    sd x7, 48(sp)
    sd x8, 56(sp)
    sd x9, 64(sp)
    sd x10, 72(sp)
    sd x11, 80(sp)
    sd x12, 88(sp)
    sd x13, 96(sp)
    sd x14, 104(sp)
    sd x15, 112(sp)
    sd x16, 120(sp)
	sd x17, 128(sp)
	sd x18, 136(sp)
	sd x19, 144(sp)
	sd x20, 152(sp)
	sd x21, 160(sp)
	sd x22, 168(sp)
	sd x23, 176(sp)
	sd x24, 184(sp)
	sd x25, 192(sp)
	sd x26, 200(sp)
	sd x27, 208(sp)
	sd x28, 216(sp)
	sd x29, 224(sp)
	sd x30, 232(sp)
	sd x31, 240(sp)
    csrr t0, sepc
    sd t0, 248(sp) 
    
    # 2. 调用 trap_handler
    csrr a0, scause
    csrr a1, sepc
    jal ra, trap_handler
    # 3. 恢复寄存器和 sepc
    #    特别注意 sp 寄存器的恢复
    ld t0, 248(sp)
    csrw sepc, t0
    ld x1, 0(sp)
    ld x2, 8(sp)
    ld x3, 16(sp)
    ld x4, 24(sp)
    ld x5, 32(sp)
    ld x6, 40(sp)
    ld x7, 48(sp)
    ld x8, 56(sp)
    ld x9, 64(sp)
    ld x10, 72(sp)
    ld x11, 80(sp)
    ld x12, 88(sp)
    ld x13, 96(sp)
    ld x14, 104(sp)
    ld x15, 112(sp)
    ld x16, 120(sp)
	ld x17, 128(sp)
	ld x18, 136(sp)
	ld x19, 144(sp)
	ld x20, 152(sp)
	ld x21, 160(sp)
	ld x22, 168(sp)
	ld x23, 176(sp)
	ld x24, 184(sp)
	ld x25, 192(sp)
	ld x26, 200(sp)
	ld x27, 208(sp)
	ld x28, 216(sp)
	ld x29, 224(sp)
	ld x30, 232(sp)
	ld x31, 240(sp)
    addi sp, sp, 256
    # 4. 返回
    sret

    .globl __dummy
__dummy:
    la t0, dummy_task
    csrw sepc, t0
    sret

    .globl __switch_to
__switch_to:
    # 1. 将当前线程的上下文保存到当前线程的 thread_struct 中

    sd ra,32(a0)
    sd sp,40(a0)
    sd s0,48(a0)
    sd s1,56(a0)
    sd s2,64(a0)
    sd s3,72(a0)
    sd s4,80(a0)
    sd s5,88(a0)
    sd s6,96(a0)
    sd s7,104(a0)
    sd s8,112(a0)
    sd s9,120(a0)
    sd s10,128(a0)
    sd s11,136(a0)


    # 2. 从下一个线程的 thread_struct 中恢复上下文
    ld ra,32(a1)
    ld sp,40(a1)
    ld s0,48(a1)
    ld s1,56(a1)
    ld s2,64(a1)
    ld s3,72(a1)
    ld s4,80(a1)
    ld s5,88(a1)
    ld s6,96(a1)
    ld s7,104(a1)
    ld s8,112(a1)
    ld s9,120(a1)
    ld s10,128(a1)
    ld s11,136(a1)

    ret